# Generated by Django 4.2 on 2023-04-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.DateTimeField(null=True),
        ),
    ]
