# Generated by Django 4.2 on 2023-05-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.TextField(null=True),
        ),
    ]
